services:
  postgres:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  app:
    container_name: game_app
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      target: dependencies
    ports:
      - "3333:3333"
      - 9229:9229
    env_file:
      - .env
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - HOST=0.0.0.0
    volumes:
      - ./:/home/node/app
    command: npm run dev # start the app in development mode

volumes:
  postgres_volume:
